name: Build and Test MonoWebshop

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm install

    - name: Install nx
      run: npm install -g nx

    - name: Build clientside project
      run: nx run webshop-clientside:build:production

    - name: Build api project
      run: nx run webshop-api:build:production

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm install

    - name: Install nx
      run: npm install -g nx

    - name: Run clientside tests
      run: nx run webshop-clientside:test:production

    - name: Run api tests
      run: nx run webshop-api:test:production
